# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

#all me!
triangles = set(n*(n+1)//2 for n in range(286, 100000))
pentagonals = set(n*(3*n-1)//2 for n in range(166, 100000))
hexagonals = set(n*(2*n-1) for n in range(144, 100000))

for t in triangles:
	if t in pentagonals and t in hexagonals:
		print(t)
		break
#1533776805

